# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_name', models.CharField(max_length=20)),
                ('pokemon_id', models.IntegerField(default=0)),
                ('pokemon_img', models.CharField(max_length=24)),
            ],
        ),
    ]
