# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20160722_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemons',
            name='pokemon_id',
        ),
    ]
