# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_pokemons_evolve_to_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemons',
            name='evolve_from_at',
            field=models.IntegerField(default=0),
        ),
    ]
