# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_auto_20160801_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemons',
            name='evolve',
        ),
        migrations.AddField(
            model_name='pokemons',
            name='evolve_from',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='evolve_from_at',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='evolve_from_pokemon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='evolve_to',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='evolve_to_at',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemons',
            name='evolve_to_pokemon',
            field=models.IntegerField(default=0),
        ),
    ]
