# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_auto_20160801_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemons',
            name='evolve_from_pokemon',
        ),
        migrations.RemoveField(
            model_name='pokemons',
            name='evolve_to_pokemon',
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='evolve_from_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_fk', to='wiki.Pokemons'),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='evolve_to_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_fk', to='wiki.Pokemons'),
        ),
    ]
