# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_auto_20160801_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemons',
            name='evolve_from',
        ),
        migrations.RemoveField(
            model_name='pokemons',
            name='evolve_to',
        ),
    ]
