# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_pokemons_pokedex_n'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemons',
            old_name='pokedex_n',
            new_name='pokedex',
        ),
    ]
