# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_auto_20160804_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemons',
            name='another_img',
            field=models.ImageField(default=None, null=True, upload_to='/static/images/'),
        ),
    ]
