# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0020_auto_20160804_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemons',
            old_name='another_img',
            new_name='image',
        ),
    ]
