# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0021_auto_20160805_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemons',
            name='id',
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='pokedex',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
