# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0022_auto_20160805_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemons',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='pokedex',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
