# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0023_auto_20160805_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex', models.IntegerField(default=0)),
                ('pokemon_name', models.CharField(max_length=20)),
                ('evolve_from_at', models.IntegerField(default=0)),
                ('evolve_to_at', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Difference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_fk', to='wiki.Change')),
                ('before', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_fk', to='wiki.Change')),
            ],
        ),
        migrations.RemoveField(
            model_name='pokemons',
            name='pokemon_img',
        ),
        migrations.AddField(
            model_name='change',
            name='evolve_from_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_ch', to='wiki.Pokemons'),
        ),
        migrations.AddField(
            model_name='change',
            name='evolve_to_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_ch', to='wiki.Pokemons'),
        ),
    ]
