# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0024_auto_20160809_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='difference',
            name='after',
        ),
        migrations.RemoveField(
            model_name='difference',
            name='before',
        ),
        migrations.AlterField(
            model_name='change',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Difference',
        ),
    ]
