# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0025_auto_20160809_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemons',
            old_name='pokemon_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='change',
            name='evolve_from_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_ch', to='wiki.Pokemons'),
        ),
        migrations.AlterField(
            model_name='change',
            name='evolve_to_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_ch', to='wiki.Pokemons'),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='evolve_from_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_fk', to='wiki.Pokemons'),
        ),
        migrations.AlterField(
            model_name='pokemons',
            name='evolve_to_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_fk', to='wiki.Pokemons'),
        ),
    ]
