# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0026_auto_20160809_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change',
            old_name='pokemon_name',
            new_name='name',
        ),
    ]
